CREATE TABLE IF NOT EXISTS metadata (
    ecli                          TEXT PRIMARY KEY,
    document_type                 TEXT DEFAULT '',
    date_decision                 TEXT DEFAULT '',
    date_publication              TEXT DEFAULT '',
    language                      TEXT DEFAULT 'nl',
    instance                      TEXT DEFAULT '',
    jurisdiction_city             TEXT DEFAULT '',
    case_number                   TEXT DEFAULT '',
    procedure_type                TEXT DEFAULT '',
    spatial                       TEXT DEFAULT '',
    domains                       TEXT DEFAULT '',
    referenced_legislation_titles TEXT DEFAULT '',
    alternative_publications      TEXT DEFAULT '',
    title                         TEXT DEFAULT '',
    full_text                     TEXT DEFAULT '',
    summary                       TEXT DEFAULT '',
    citing                        TEXT DEFAULT '',
    cited_by                      TEXT DEFAULT '',
    legislations_cited            TEXT DEFAULT '',
    predecessor_successor_cases   TEXT DEFAULT '',
    url_publications              TEXT DEFAULT '',
    info                          TEXT DEFAULT '',
    source                        TEXT DEFAULT 'Rechtspraak'
);
