CREATE TABLE IF NOT EXISTS metadata (
    ecli                 TEXT PRIMARY KEY,
    issued               TEXT DEFAULT '',
    language             TEXT DEFAULT 'nl',
    creator              TEXT DEFAULT '',
    date_decision        TEXT DEFAULT '',
    zaaknummer           TEXT DEFAULT '',
    type                 TEXT DEFAULT '',
    procedure            TEXT DEFAULT '',
    spatial              TEXT DEFAULT '',
    subject              TEXT DEFAULT '',
    relation             TEXT DEFAULT '',
    "references"         TEXT DEFAULT '',
    hasVersion           TEXT DEFAULT '',
    link                 TEXT DEFAULT '',
    title                TEXT DEFAULT '',
    inhoudsindicatie     TEXT DEFAULT '',
    info                 TEXT DEFAULT '',
    full_text            TEXT DEFAULT '',
    jurisdiction_country TEXT DEFAULT '',
    source               TEXT DEFAULT 'Rechtspraak',
    citations_incoming   TEXT DEFAULT '',
    citations_outgoing   TEXT DEFAULT '',
    legislations_cited   TEXT DEFAULT '',
    summary              TEXT DEFAULT '',
    bwb_id               TEXT DEFAULT ''
);
